apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mjpeg-server
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mjpeg-server
    spec:
      containers:
      - name: mjpeg-server
        image: viros/is-mjpeg-server:1
        env:
        - name: IS_URI
          value: 'amqp://rabbitmq.default'
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mjpeg-server
  namespace: default
spec:
  type: NodePort
  selector:
    app: mjpeg-server
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300