apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.12
        ports:
        - containerPort: 9411
        resources:
          limits:
            memory: 4Gi
            cpu: 1000m

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-ui
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-ui
    spec:
      containers:
      - name: zipkin-ui
        image: openzipkin/zipkin-ui:2.12
        env:
        - name: ZIPKIN_BASE_URL
          value: http://zipkin.default:9411
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: default
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - name: http
      protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30200

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: zipkin-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30280
